version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    volumes:
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./server
    environment:
      DATABASE_URL: postgres://user:password@db:5432/tasks
      JWT_SECRET: supersecret
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - backend

